[package]
name = "rescrobbled"
version = "0.4.0"
authors = ["Koen Bolhuis <koen.bolhuis@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/InputUsername/rescrobbled.git"
homepage = "https://github.com/InputUsername/rescrobbled"
readme = "README.md"
description = "MPRIS music scrobbler daemon"
keywords = ["mpris", "music", "scrobble", "daemon"]
categories = ["multimedia", "command-line-utilities"]
publish = true

[dependencies]
mpris = "2.0.0-rc2"
rustfm-scrobble = "1"
listenbrainz-rust = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
dirs = "3"
notify-rust = "4"

[dev-dependencies]
tempfile = "3"
