[package]
name = "rescrobbled"
version = "0.8.0"
authors = ["Koen Bolhuis <koen.bolhuis@gmail.com>"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/InputUsername/rescrobbled.git"
homepage = "https://github.com/InputUsername/rescrobbled"
readme = "README.md"
description = "MPRIS music scrobbler daemon"
keywords = ["mpris", "music", "scrobble", "daemon"]
categories = ["multimedia", "command-line-utilities"]
publish = false

[dependencies]
mpris = "2.0.0"
rustfm-scrobble-proxy = "2.0.0"
listenbrainz = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"
dirs = "4.0.0"
anyhow = "1.0.55"
rpassword = "6.0.1"

[dev-dependencies]
tempfile = "3.3.0"
